### ISSUE TITLE
YouthAgeGroup - no element for the group counts

### ISSUE THREAD

**Issue by amymallen** [hmis-interop/xml#100]
YouthAgeGroup documentation says:
Of the youth beds what number are restricted to: 
	1 = Only under age 18 
	2 = Only ages 18 to 24 
	3 = Only youth under age 24 (both of the above)

YouthBedInventory is the total of all youth beds.

There are not elements for the count of beds for each YouthAgeGroup as the documentation suggests.

**Comment by eric-jahn** [comment]
This is for XSD 4.0.1, I assume, but I think it also applies to 4.1.1.  YouthBedInventory is the inventory count for that specific age group selected.  You should make a new BedInventory element for each Youth Age Group you need to transmit.  Check out the sample XML: 

`<hmis:BedInventory>
                    <hmis:BedInventory>130</hmis:BedInventory>
                    <hmis:CHBedInventory>17</hmis:CHBedInventory>
                    <hmis:VetBedInventory>14</hmis:VetBedInventory>
                    <hmis:YouthBedInventory>16</hmis:YouthBedInventory>
                    <hmis:YouthAgeGroup>1</hmis:YouthAgeGroup>
                </hmis:BedInventory>`

We probably could have made it clearer by making the age group dependent upon the youth inventory and making it a choice between all the different types, like CH, Youth, Vet, etc..  This way is more compact, but clarity should prevail.  I'll make an issue for the future, but it shouldn't be a deal breaker, just could be clearer.
