### ISSUE TITLE
How should required elements be handled if there is no 99?

### ISSUE THREAD

**Issue by amymallen** [hmis-interop/xml#101]
This relates specifically to the elements under ExitPlansActions starting with WrittenAftercarePlan. If the users has not answered all of the questions, the elements are required, but they are Yes, No, and Refused. There is no Data Not Collected option.

**Comment by eric-jahn** [comment]
So this is related to the 2014 v3.0 Data standard, and the 4.0.1 XML Schema version.  Looking at the [May 2014 v3.0 Data Dictionary](https://github.com/servinglynk/hmis-lynk-open-source-docs/raw/master/doc/WikiContent/HMIS%2BData%2BDictionary%2BPOSTED%2B5%2B1%2B2014%2B_May%2B1%2B2014_.pdf) for that, it the following, which doesn't show a "Data Not Collected" option: 

4.36 Transitional, Exit-care or Aftercare Plans and Actions
Element Name Transitional, Exit-care or Aftercare Plans and Actions
Field & Response(s) 1 A written transitional, aftercare or follow-up plan or agreement
0 No
1 Yes
9 Client refused
Field & Response(s) 2 Advice about and/or referral to appropriate mainstream assistance programs
0 No
1 Yes
9 Client refused
