### ISSUE TITLE
hmis:noPointsYes

### ISSUE THREAD

**Issue by rayhayes** [hmis-interop/xml#120]
Where is the value for noPointsYes defined? I see the reference in the xsd but I don't find it in the data dictionary. Thanks.

**Comment by rayhayes** [comment]
Not finding it at http://www.hudhdx.info/Resources/Vendors/2017_1_2_1/HUD_HMIS.xsd

**Comment by eric-jahn** [comment]
@rayhayes, it's not directly defined in the Data Dictionary in one place, but it represent a common set of responses used in the Data Dictionary, which is: 
0 No (0 points)
1 Yes
You'll see Data Dictionary references in the XML Schema annotations in places like: 
https://github.com/hmis-interop/xml/blob/v6.1.1/src/HUD_HMIS.xsd#L728 which is on page 105 of https://www.hudexchange.info/resources/documents/HMIS-Data-Dictionary.pdf  (search for V7 SSVF HP Targeting Criteria, Field 1 & Responses, Field 3 & Responses, etc.).   So, we just made a data type called hmis:noPointsYes and reuse that whenever
0 No (0 points)
1 Yes
is needed.  Does this make sense?

**Comment by rayhayes** [comment]
Makes sense but it makes it hard to used the xsd in any xml tooling that validates the xsd document given that certain types are undefined. I can fix the issues by adding definitions for all the types that are undefined and I'll post a followup question with my assumptions so you can validate them. Thanks for the quick reply.

**Comment by eric-jahn** [comment]
No it's already defined in the xsd.  See the enumeration at https://github.com/hmis-interop/xml/blob/v6.1.1/src/HUD_HMIS.xsd#L4863 for noPointsYes's type definition.  All the types are defined.  You had asked about where it was defined in the Data Dictionary (which is a plain English doc), so I didn't mention its definition in the XML Schema.

**Comment by rayhayes** [comment]
You're right. Found it. Thanks for the pointer. For some reason the editor wasn't finding that last occurrence of the noPointsYes.
