### ISSUE TITLE
hmis:Contact seems to be missing

### ISSUE THREAD

**Issue by andrewfulrich** [hmis-interop/xml#121]
Hey, I'm new to this, but it looks like hmis:Contact is not defined in the xsd even though there's a keyref  saying it refers to an hmis:Enrollment and also an assertion dealing with it.  It's defined in the data dictionary (4.12), so shouldn't it be here?

**Comment by eric-jahn** [comment]
@andrewfulrich , I think that assertion needs to be cleaned up.  4.12 Contact is just a RecordType = 13 .  See: https://github.com/hmis-interop/xml/blob/8963ecabb09dba89597967c85a2f04e2d9d4cfdf/src/HUD_HMIS.xsd#L2166

**Comment by eric-jahn** [comment]
btw, here is the contact element reference removal commit I just made: 05d4cd0a19f45bfda02e4fdf6564b2acbbd4cf5c .  I didn't increment the tag version #, since it doesn't affect what the resulting XML looks like, but this change is made and committed.

**Comment by andrewfulrich** [comment]
Great thanks very much!
