### ISSUE TITLE
keyrefs to be removed?

### ISSUE THREAD

**Issue by andrewfulrich** [hmis-interop/xml#122]
It looks like enrollmentFormerWardChildWelfareKeyRef and enrollmentFormerWardJuvenileJusticeKeyRef have selectors which are elements within a complex type rather than types themselves. Do these need to be cleaned out as well?

**Comment by eric-jahn** [comment]
@andrewfulrich Yes, they do need to be cleaned out.  Those haven't had their own complex type for since version 4!  I think what I have to do is go through the whole list of keys and keyrefs, and remove unneeded ones.  They shouldn't affect anything, but tidier is always better and less confusing.
