### ISSUE TITLE
housing assessment disposition

### ISSUE THREAD

**Issue by jimosullivan1099** [hmis-interop/xml#132]
Hi Eric,

It looks like housing assessment disposition is still in the XSD, but it was removed from the 2020 data standards as far as I understand.

Jim

**Comment by eric-jahn** [comment]
@jimosullivan1099 I think you are correct.  Now it's just "Housing Assessment At Exit W5.1".  Removing https://github.com/hmis-interop/xml/blob/FY2020/src/HUD_HMIS.xsd#L1634-L1638 .
