### ISSUE TITLE
personHistorical/PriorResidence maxOccurs is unbounded

### ISSUE THREAD

**Issue by MollyMcEvilley** [hmis-interop/xml#14]
PriorResidence is specific to program entry and should have one and only one value per program entry, but the maxOccurs is unbounded and it occurs within PersonHistorical, where the maxOccurs is also unbounded.

**Comment by eric-jahn** [comment]
Oops, sorry, that last message about https://github.com/hmis-interop/xml/commit/80997d13dec0824e1345564e96669abfca947aba fixing this issue was an error.  It fixed Issue #106 .
