### ISSUE TITLE
add SHA 256 option to hashstatus

### ISSUE THREAD

**Issue by eric-jahn** [hmis-interop/xml#150]
So that hash status 1-4 is available, as with the CSV.  SHA-256 isn't currently an explicit option (right now, you'd have to use "other" for  SHA-256).

**Comment by nataliesus-dev** [comment]
Hi Eric!
Just want to confirm hash will be fixed for both schemas: FY 2020 and FY 2022. Correct?

**Comment by eric-jahn** [comment]
Yes, or even further back, depending on where it started.
