### ISSUE TITLE
XML FY2022: a few column name changes for <Enrollment> are missing

### ISSUE THREAD

**Issue by nataliesus-dev** [hmis-interop/xml#154]
Hi @eric-jahn ,

According to CSV 2022 (https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.0.pdf) a few columns in Enrollment.csv were **renamed**:
- MentalHealthIssuesFam into MentalHealthDisorderFam
- AlcoholDrugUseDisorderFam into AlcoholDrugUseDisorderFam

CSV:
![image](https://user-images.githubusercontent.com/64896441/127650949-693f795a-de76-4197-b59b-a133afbe693c.png)

XML:
![image](https://user-images.githubusercontent.com/64896441/127651317-6da1ce54-8e08-4911-b86b-95b1d6b8851c.png)

Could you please advise if XML schema will be updated?

Thank you!

**Comment by eric-jahn** [comment]
I changed MentalHealthIssuesFam into MentalHealthDisorderFam, but "AlcoholDrugUseDisorderFam into AlcoholDrugUseDisorderFam" appears to not require a change.
