### ISSUE TITLE
XML FY2022: <VerifiedBy> - shouldn't type be changed from string50 to string100?

### ISSUE THREAD

**Issue by nataliesus-dev** [hmis-interop/xml#155]
Hi @eric-jahn ,

This ticket is related to https://github.com/hmis-interop/xml/issues/153 where ProjectName should be changed from string50 to string100 so I think <VerifiedBy> should also be changed from string50 to string100? Could you please advise? Thank you!

![image](https://user-images.githubusercontent.com/64896441/127656325-d9e05ad3-1bee-4107-9752-6d1e45bfb825.png)

**Comment by eric-jahn** [comment]
I see that this is not a CSV/XML divergence, but rather an overall specification ambiguity.  I'm not sure if the Dictionary and CSV intended the Continuum projects' IDs (string 32) or their names (string 100).  I'd recommend using IDs.  So, I agree, either way, it should be changed, but I would think the project IDs would be more concise and easier to match with fewer errors than full names.  But, I'll ask HUD about this and coordinate a fix which would also include a potential change to the CSV.

**Comment by eric-jahn** [comment]
Resolved: https://github.com/hmis-interop/xml/commit/c2782c4f04c54726fe73e2576f8e789d78f9d016
