### ISSUE TITLE
HUD_HMIS_Instance.xml - unexpected <VerifiedBy> value

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#159]
Hi @eric-jahn ,

Could you please take a look at HUD_HMIS_Instance.xml? It looks like <VerifiedBy> is as a string of several CoCs ( I confirmed there is no program with “BZ-123,MA-500” project name or project id in the xml file).

![image](https://user-images.githubusercontent.com/28144855/129694630-484fd944-ce6c-4358-a063-4f6ed25bab09.png)

Thank you!
Natalie

**Comment by nataliesus** [comment]
Just in case, should <VerifiedBy> be CoC? In our system we select Project.

**Comment by eric-jahn** [comment]
Oh, that's right.  I'll use a project name instead.
