### ISSUE TITLE
HUD_HMIS-for-logical-model.xsd: <VerifiedBy> should be fixed from string50 to string100

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#160]
Hi @eric-jahn ,

<VerifiedBy> in HUD_HMIS.xsd has been updated recently from string50 to string100.

I wonder if the same update should be done in HUD_HMIS-for-logical-model.xsd? Please advise.

Best regards,
Natalie

**Comment by eric-jahn** [comment]
@nataliesus Yes, I think they should be synchronized.  However, I think I found an easier way to reference the HMIS Schema types from the RDF model, using this method in section 2.3 here: https://www.w3.org/TR/swbp-xsch-datatypes/ .  So, I think I might be able to just delete the XSD used for the logical model.
