### ISSUE TITLE
HUD_HMIS_Instance.xml: datetime format and date logic

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#161]
Hi @eric-jahn ,

1. Could you please advise if datetime format should be the same for all DateTime elements/attributes? i.e. some of them have "Z" at the end. 
![image](https://user-images.githubusercontent.com/28144855/129696612-e798983c-0aed-423f-bb71-eb5f1fccec4c.png)

2. Not sure how it is possible to include data submitted after the export period. Could you please take a look?
![image](https://user-images.githubusercontent.com/28144855/129696977-7ee673ed-2249-4e47-973c-fb58811ba5e4.png)

Best regards,
Natalie

**Comment by eric-jahn** [comment]
For the first item, we just use ttps://en.wikipedia.org/wiki/ISO_8601 , and there are many permissable variants of the data-time representation, depending on specificity, etc..  The Z is optional, I believe.  As long is it is a valid date-time per ISO 8601, it should validate and be parsed.

For the second item, I just use randomly generated data, which sometimes is not consistent with the export data range.  If there is time, I might be able to make them more consistent.  But there is no validation in place to catch those inconsistencies.
