### ISSUE TITLE
XML and CSV has 3 income fields with different names

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#162]
Hi @eric-jahn ,

IncomeBenefits.csv (https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.0.pdf) has fields:

- Other**Income**Source
- Other**Income**Amount
- Other**Income**SourceIdentify

<incomeAndSources> in XML (https://github.com/hmis-interop/xml/blob/main/src/HUD_HMIS.xsd) use different fields names:

- OtherSource
- Other**Source**Amount
- OtherSourceIdentify
![image](https://user-images.githubusercontent.com/28144855/129866859-44f5f603-9dfd-4071-b542-a7c5ec377a56.png)

I wonder shouldn't both XML and CSV use the same field names? Please advise.

**Comment by eric-jahn** [comment]
Yes, they should be the same.  Good catch, and fixed :)

**Comment by nataliesus** [comment]
Hi Eric!

Could you please fix it for FY 2020 as well? Thanks a lot!
