### ISSUE TITLE
AftercareProvided element case question

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#163]
Hi @eric-jahn ,

Not an issue, but shouldn't After**C**areProvided be After**c**areProvided?

![image](https://user-images.githubusercontent.com/28144855/129872290-b728304f-72c1-4306-83fc-84a71a995d24.png)

**Comment by eric-jahn** [comment]
Yes, I'll make the change, since it should match the CSV element name.

**Comment by eric-jahn** [comment]
Fixed by 19cc1190f0baa17824f6baae98b44f74bcf69e3e

**Comment by nataliesus** [comment]
Hi @eric-jahn !

Could you please fix FY2020 as well? Thank you!

**Comment by eric-jahn** [comment]
FY2020 fixed as well!

Eric Jahn
CTO/Data Architect
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com
