### ISSUE TITLE
Source -> SoftwareVersion:  small difference between XML and CSV

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#165]
Hi @eric-jahn ,

In CSV spec SoftwareVersion is **optional**:
![image](https://user-images.githubusercontent.com/28144855/130032801-44627846-adfa-4bdb-88e5-48ac863e4bb0.png)

But in XML schema SoftwareVersion is **mandatory**:
![image](https://user-images.githubusercontent.com/28144855/130032761-420cb563-e7a8-437d-9c4f-4d0270d5c3b9.png)

Could you please take a look?

Also, in CSV spec, SoftwareVersion field type is S50. In XML spec, SoftwareVersion field type is xs:string. Should the XML schema be updated using string50 type for SoftwareVersion? Please advise.

Best regards,
Natalie

**Comment by eric-jahn** [comment]
Yes, they should match.

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

Should this fix be applied to v2020?

Best regards,
Natalie

**Comment by nataliesus** [comment]
Hi @eric-jahn,

"hmis:string50" was added to FY2020. But what is about minOccurs="0"? I believe it should be added too.
