### ISSUE TITLE
AssessmentResults and AssessmentQuestions: required/optional discrepancy between XML and CSV

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#172]
Hi @eric-jahn ,

### AssessmentResults

According to XML schema (both FY2020 and FY 2022):

- AssessmentResultType field could be NULL
- AssessmentResult field is required

![image](https://user-images.githubusercontent.com/28144855/131322075-0f94a603-1e1b-4f07-9c9c-c57650ff91bc.png)

But CSV spec instructions are different:

- AssessmentResultType field is required
- AssessmentResult field could be NULL or could be required

![image](https://user-images.githubusercontent.com/28144855/131322184-2979c59a-ba4f-4bd7-859e-df41ca4f2da9.png)

### AssessmentQuestions

In XML schema:

- AssessmentQuestion field is required
- AssessmentAnswer field is required
![image](https://user-images.githubusercontent.com/28144855/131328522-66c9088c-0b9d-4886-8a78-58b60e6af448.png)

In CSV spec:
- AssessmentQuestion field is optional
- AssessmentAnswer field is optional
![image](https://user-images.githubusercontent.com/28144855/131328599-b7543dc0-d9aa-4f4e-ae82-a221eddf3226.png)

Could you please take a look? If XML schema should be updated, please update both FY2020 and FY 2022 and re-generate documents.

Thank you!
Natalie

**Comment by eric-jahn** [comment]
Good catches.  Fixing now!  I'll regenerate the docs, after I push all changes.

**Comment by nataliesus** [comment]
Hi @eric-jahn !

Confirm AssessmentResultType and AssessmentResult were fixed.

But what is about AssessmentQuestion and AssessmentAnswer? Could you please take a look?

Thank you,
Natalie

**Comment by eric-jahn** [comment]
The main branch is only used for development in this repository (synched up typically right before a Data Standard year is branched off).  The versioned brnach repositories for each year are the maintained repositories (maintained over the years).  I wouldn't check out main.  Sorry, I missed the AssessmentQuestions/Answer fixes.  Will look into this now.

**Comment by eric-jahn** [comment]
I'm going to check with HUD TA on these, since the CSV docs also state 
"For each row in Assessment.csv, there must be at least 1 row in AssessmentQuestions.csv, i.e. every assessment must have at least one question and answer."

I also see the local determination asterisk you pointed out, which seems contradictory. 

It says the same for AssessmentResults, so I just want to verify before I finish these changes.

**Comment by eric-jahn** [comment]
Update, still checking on these with HUD TA, but for now, based on the discussion so far, it looks like we are making 4.19.5/A/6/B all required if the record exists.  But, the community can decide whether AssessmentQuestions and AssessmentResults need to be present at all.

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

Do you have any update from HUD TA? With your last commint you made changed for FY2022, what is about FY2020?

Best regards,
Natalie

**Comment by eric-jahn** [comment]
I will ask for an update now and post back here.

Eric Jahn
CTO/Data Architect
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by eric-jahn** [comment]
@nataliesus I just got an update for you.  This issue is going to result in changes to the XML and CSV.  I'll make the XML changes soon to match what the CSV changes.  Details below (DRAFT, not official).

> Only fields 1, 2, 3, 4, and 7 are “required” for HUD APRs for funded CE projects
>  
> Revise the CSV upper text to read "For each row in Assessment.csv, there may be corresponding rows in each of AssessmentQuestions.csv, and AssessmentResults.csv, as locally determined by the community.  However, if there are any AssessmentQuestions records, they must each have at least a question and an answer."
> 
> And then in the AssessmentQuestions.csv table, it should instead have: 
> 
> 4.19.5 AssessmentQuestion | S250 | * | Null = N/blank (and remove the asterisk from nillable column, because the community can skip the entire record, but if they don't skip it, then they must have a complete record with a Question)
> 
> 4.19.A AssessmentAnswer | S500 | * | Null = N/blank (and remove the asterisk from nillable column, because the community can skip the entire record, but if they don't skip it, then they must have a complete record with an Answer)
> 
> 
> And then in the AssessmentResults.csv table, it should instead have: 
> 
> 4.19.6 AssessmentResultType | S250 | * (add an asterisk to List Type) | Null = N/blank (stays the same, because the community can skip the entire record, but if they don't skip it, then they must have a complete record with an AssessmentResultType)
> 
> 4.19.B AssessmentResult | S250 | * (stay same) | Null = N/blank (and remove the asterisk from nillable column, because the community can skip the entire record, but if they don't skip it, then they must have a complete record with an AssessmentResult)
> 
>

**Comment by eric-jahn** [comment]
Closing this issue, since the FY2020 and FY2022 XML Schemas are in alignment with the directives above, and waiting for the CSV to be updated.

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

Do you have any idea when CSV will be updated? https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.1_clean.pdf still has * fory Null column.

**Comment by eric-jahn** [comment]
@nataliesus It's still being actively discussed, but soon I think. XML will
match, right after CSV comes out.  :)

**Comment by eric-jahn** [comment]
FY2022 synch up woth CSV v1.2: https://github.com/hmis-interop/xml/commit/b6043b9c8262a5699a335b1f5ae79fe2a7f115af

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

Will you update FY2020?

**Comment by eric-jahn** [comment]
I had reviewed FY2020 and couldn't see any changes.  2022 adds a little
more restriction.

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

FY2020 doesn't have minOccurs="0" for AssessmentAnswer and for AssessmentResult we expected to have (it was a problem described in the task description).
https://github.com/hmis-interop/xml/blob/FY2020/src/HUD_HMIS.xsd
![image](https://user-images.githubusercontent.com/28144855/134902736-c3ae027d-2e4b-4368-b0b8-a7e902304e5c.png)

Could you please take a look?

**Comment by eric-jahn** [comment]
FY2020 CSV has * (local definition) for those two elements.  Because of that, I have to allow for the least restrictive possibility (minOccurs="0").  FY2022 was more clear on this matter, so it's a more restrictive/specific.

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

So you will re-open this ticket and fix FY2020, correct?

**Comment by eric-jahn** [comment]
@nataliesus Yes, correct, but I am going to bundle these changes weekly moving forward.

**Comment by eric-jahn** [comment]
I think you'll need to change it in your local copy, in that case.

Eric Jahn
CTO/Data Architect
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com
