### ISSUE TITLE
FY 2022: exportDirective should be int to be consistent with CSV

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#178]
Hi @eric-jahn ,

Previously, you updated exportPeriodType from string values to int values.

Could you please take a look at exportDirective as well? CSV exports int value. But XML - string value.

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

Thank you for update!

Just in case, you reworked ExportPeriodType under https://github.com/hmis-interop/xml/issues/152 and made it type=integer for FY 2022 only:
![image](https://user-images.githubusercontent.com/28144855/131802799-e68931f4-fb4d-4e5a-b338-bf51e500e1eb.png)

But similar update for exportDirective was done for both FY2020 and FY2022. I wonder if ExportPeriodType should be int for FY2020 also? Could you please take a look?

Thank you!

**Comment by eric-jahn** [comment]
Oops, I committed this [change](https://github.com/hmis-interop/xml/commit/f52ae3fd6d42c7e83dfe3b89b3cc5d5393ee3e7c) to FY2020 yestederday, but forgot to mention this issue in the commit note.  

> Hi @eric-jahn ,
...
> But similar update for exportDirective was done for both FY2020 and FY2022. I wonder if ExportPeriodType should be int for FY2020 also? Could you please take a look?
> 
> Thank you!
