### ISSUE TITLE
FY2022: DisabilityType label name changes needed

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#180]
Hi @eric-jahn ,

Could you please rename option labels in XML FY2022 to match CSV FY2022?
![image](https://user-images.githubusercontent.com/28144855/131865877-ad22bf04-f9eb-4c14-807e-b3c071885e8c.png)

Thank you!
Natalie

**Comment by eric-jahn** [comment]
Fixed with https://github.com/hmis-interop/xml/commit/b1138dc3563f05d0cf884e9e97c7a32ba73cd1c4#diff-1774cfe9242cb3bf1a434964da266bcebd449090af84dc1cfb84e0fa1ae9af9f
