### ISSUE TITLE
HPScreeningScore: element type is different between CSV and XML

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#181]
Hi @eric-jahn ,

There is a discrepancy between XML and CSV specs in HPScreeningScore field type.

XML:
![image](https://user-images.githubusercontent.com/28144855/132014612-8e3fff6d-f77e-466c-8af5-8fdd61037c2c.png)

CSV:
![image](https://user-images.githubusercontent.com/28144855/132014630-d90369b1-b91a-44d8-aaef-c4fd973276e3.png)

Could you please take a look if HPScreeningScore in XML should be corrected? Please update both FY2020 and FY2022 if needed.

Thank you!
Natalie

**Comment by eric-jahn** [comment]
Yes, it looks like the previous 2 value restriction was relaxed to an integer starting FY2020.

**Comment by nataliesus** [comment]
Thank you, @eric-jahn! It looks like this ticket can be closed now.
