### ISSUE TITLE
ExitRHY: list of mandatory fields is different between FY2020 and FY2022

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#184]
Hi @eric-jahn ,

XML FY2020 has mandatory fields that are optional in CSV and also optional in XML FY2022.

FY2020:
![image](https://user-images.githubusercontent.com/28144855/132342708-cec086e5-18c8-4e3c-8e23-1c21508c7bda.png)
FY2022:
![image](https://user-images.githubusercontent.com/28144855/132342743-43a8df06-7444-4353-a831-c36f24089889.png)

Maybe you can make them optional in FY2020 and re-generate the documentation file?

Thank you,
Natalie

**Comment by eric-jahn** [comment]
I can only change the XML based on incongruities with the Data Dictionary (main reason) or CSV (secondary reason).  I'll check the CSV for FY2020 to verify the differences.
