### ISSUE TITLE
IncomeAndSources: list of mandatory fields is different between XML and CSV

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#186]
Hi @eric-jahn ,

IncomeAndSources has many mandatory fields that are optional in CSV. Shouldn't they be consistent with CSV? Please advise.

XML
![image](https://user-images.githubusercontent.com/28144855/132350607-6e5140a4-b717-42f9-b97e-927c7341df68.png)

CSV
![image](https://user-images.githubusercontent.com/28144855/132350637-71b08580-e2e1-4f62-b9c3-dbd86dd320a6.png)

Maybe _IncomeFromAnySource_ should be mandatory but other fields should be optional? 

Best regards,
Natalie

**Comment by eric-jahn** [comment]
From the FY2022 Data Standards Manual v1.1: "If there is a "no" response to 'Income from Any Source' then the HMIS must automatically record all sources as "no" and leave dollar amounts null of $0.00.", so they all have to be mandatory.  Changing so that this is so.

**Comment by eric-jahn** [comment]
I'm realizing I shouldn't have made this change.  IncomeFromAnySource and related fields are required to have a values, per the FY2020 HMIS Data Standard.  CSV may not require it, because the table is denormalized with the other benefits, so they need to be nillable to skip them.  But the XML, the whole IncomeAndSources data element can be independently skipped.

**Comment by nataliesus** [comment]
Hi @eric-jahn ,
But if 'Income from Any Source' = Data not collected, or Rejected, then other fields are not asked so they must be optional, correct?

**Comment by eric-jahn** [comment]
Oh right, for 8/9/99 values, they would be optional.  Oh, good, I can keep
this change.  Thank you! :)

Eric Jahn
CTO/Data Architect
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by eric-jahn** [comment]
Except IncomeFromAnySource need to be made mandatory.
