### ISSUE TITLE
ProjectCoC: discrepancy between XML and CSV

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#189]
Hi @eric-jahn !

**#1.** Geocode is optional in XML but mandatory in CSV
XML:
![image](https://user-images.githubusercontent.com/28144855/132505981-5f64fd36-e69d-4781-a64a-e72edaa17358.png)
CSV:
![image](https://user-images.githubusercontent.com/28144855/132506000-85b01b99-e450-41fe-bdaa-25dd969f601e.png)

**#2.** informationDate is required in XML but doesn't exist in CSV
XML:
![image](https://user-images.githubusercontent.com/28144855/132506138-ccb77000-24d2-4bf4-97cc-653afb175a2b.png)

#3. Geocode pattern.
In XML schema, there is the pattern:
![image](https://user-images.githubusercontent.com/28144855/132506240-5e49909c-2ad6-487a-aad5-53e3577f1a31.png)
n the document generated following XML schema, there is another pattern:
![image](https://user-images.githubusercontent.com/28144855/132506266-e374cb8f-b04e-40a8-8b7b-82df2f85de43.png)
In CSV spec, Geocode has the next pattern:
![image](https://user-images.githubusercontent.com/28144855/132506313-8f055de5-2c80-4e58-9f7e-9bcd17ffcf86.png)

Could you please take a look?

Thank you!
Natalie

**Comment by eric-jahn** [comment]
For the regex match pattern, I experimented with adding the ^ and $ character, and it broke the validation.  Regex start/end must be implied in XSD?  Anyway, I was able to fix the hmis:geocode documentation facet pattern by removing any redundancies within the restriction.  I did that by not specifying either sign or character restrictions in the base, which the pattern then covers fully.
