### ISSUE TITLE
StartDate & EndDate: element type issue

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#195]
Hi @eric-jahn ,

Could you please take a look why report start & end dates are "dateTime" format and not "date"?
![image](https://user-images.githubusercontent.com/28144855/133629264-11c45e7c-3851-4765-8dd2-7acad31c00d5.png)

In CSV these fields use Date format:
![image](https://user-images.githubusercontent.com/28144855/133630202-934160c5-6d44-459e-9ca4-ca5a68e8b58c.png)

Both FY2020 and FY2022 should be fixed.

Thank you!
Natalie

**Comment by nataliesus** [comment]
Hi @eric-jahn ,
Any update?

**Comment by eric-jahn** [comment]
Hello, yes, this change will be made with the next set of updates, coming
soon.
