### ISSUE TITLE
WorkPlaceViolenceThreats and WorkplacePromiseDifference: different case for "p" in "place"

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#196]
Hi @eric-jahn !

Could you please advise? XML uses exactly the same upper/lower case as CSV for next fields:

- Work**P**laceViolenceThreats
- Work**p**lacePromiseDifference

Shouldn't it be either "Place" (upper case for "p") or "place" (lower case for "p") in both fields?

Thank you!

**Comment by eric-jahn** [comment]
Confirmed this will be fixed both in the XML and CSV asap (both will have lower case "p").

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

Just in case, should it also be corrected in FY2020, not FY2022 only?

**Comment by eric-jahn** [comment]
Oops, I just realized, no, I need to leave the FY2020 XML in sync with the CSV from that period.  So, if the FY2020 CSV was inconsistently cased, I need to leave the XML the same, unless the FY2020 CSV is updated.  However, I don't know if old CSV versions are still under maintenance.  FY2022 CSV "Workplace" letter cases are is being made consistent, I believe, and the XML will be released when that comes out.
