### ISSUE TITLE
IndefiniteAndImpairs - a few types are missing 

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#197]
Hi @eric-jahn ,

In new XML FY2022 there are types:

- indefiniteAndImpairsPhysicalDisability
- indefiniteAndImpairsChronicHealthCondition
- indefiniteAndImpairsMentalHealthDisorder
- indefiniteAndImpairsSubstanceUseDisorder

But I cannot find types:
- indefiniteAndImpairsDevelopmentalDisability
- indefiniteAndImpairsHIVAIDS

Could you please take a look?

**Comment by eric-jahn** [comment]
Thanks @DaviDurki !
