### ISSUE TITLE
serviceFAReferral: FAAmount - wrong text in annotation

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#199]
Hi @eric-jahn ,

It looks like a copy/paste issue in annotation for FAAmount. I believe possible values can be:
- fAAmountHOPWA
- fAAmountSSVF

![image](https://user-images.githubusercontent.com/28144855/134901032-a1641e47-2ba9-4188-b77d-acf5d023c6c4.png)
![image](https://user-images.githubusercontent.com/28144855/134901110-f17b618e-7ae0-4649-be35-1616ddf02051.png)

Best regards,
Natalie

**Comment by eric-jahn** [comment]
Types begin with lowercase to differentiate then grub the actual elements.

**Comment by eric-jahn** [comment]
Differentiate *them from*, I meant, sorry.

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

I've noticed this ticket was closed, But what is about annotation for FAAmount? WIll it be corrected?

**Comment by eric-jahn** [comment]
The annotation is referencing the fAAmount[HOPWA|SSVF] type, so it needs to be lower case.

**Comment by nataliesus** [comment]
_The annotation is referencing the fAAmount[HOPWA|SSVF] type, so it needs to be lower case._

Cannot see it here:
![image](https://user-images.githubusercontent.com/28144855/134922604-1a53372f-2ef6-4100-99a9-c5c8ca0f4836.png)

**Comment by nataliesus** [comment]
BTW, my question about lower case was removed just after I submitted the original question.

**Comment by eric-jahn** [comment]
FAAmount in that place is an element reference, within the
serviceFAReferral type.

Eric Jahn
CTO/Data Architect
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com
