### ISSUE TITLE
FY2020: PathStatusID - Shouldn't it be PATHStatusID?

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#200]
Hi @eric-jahn ,

There is **Path**StatusID element in XML schema FY2020. But it is **PATH**StatusID element in XML schema FY2022.

Can XML schema FY2020 be updated using **PATH**StatusID?

Thank you,
Natalie

**Comment by eric-jahn** [comment]
Agreed, yes, I will update that element to PATHStatusID for FY2020, since there is no CSV equivalent for it in FY2020.
