### ISSUE TITLE
Inventory - difference between XML schema and CSV spec

### ISSUE THREAD

**Issue by nataliesus** [hmis-interop/xml#201]
Hi @eric-jahn ,

Inventory.csv has ProjectID and CoCCode elements (https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.2_clean.pdf),

XML FY2020 matches the spec. But XML FY2022 does not match the CSV spec - there is ProjectCoCID instead of ProjectID and CoCCode.
![image](https://user-images.githubusercontent.com/28144855/134918737-05df9e48-4772-422d-8d2f-693c8f95d532.png)

I wonder can you update FY 2022 to match CSV spec and have  ProjectID and CoCCode instead of ProjectCoCID? I will definitely help our programmed logic.

Best regards,
Natalie

**Comment by eric-jahn** [comment]
It has to do with the normalization of the Logical Model that CSV does, so
it skips certain IDs.  That way, the CSV has a smaller number of files.
But in the Logical Model, there is a ProjectCoC class, which then can have
an ID.  There are many other places where normalization causes fewer IDs
than the LM and XML Schema.

Eric Jahn
CTO/Data Architect
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by nataliesus** [comment]
Hi @eric-jahn ,

About ProjectCoC.csv:

1. in the spec it is said "there must be at least one record and may be multiple records in ProjectCoC.csv for each record in Project.csv".
2. there are fields: ProjectCoCID, ProjectID, CoCCode, Geocode, and other address fields

As I understand, it is clear that 1 Project must have 1+ records in  ProjectCoC per each CoCCode.

But what is there are more than 1 address is associated with the Project? In this case, should I:
- a) either use the most recent address per Project
- b) or use the most recent address per Project for the reporting CoCCode
- c) or include all associated with the Project address records?

It looks like we use option c) so if Project has 1 CoCCode and 2 address records, there is 2 records in ProjectCoC.csv for the same  ProjectID and CoCCode but for two different addresses.

I think we should use option b). Could you please advise?

Thank you,
Natalie

**Comment by eric-jahn** [comment]
Hello @nataliesus , I can only answer questions specific to the XML format.  I think this one needs to be directed back to HUD HMIS AAQ, since it is about HMIS data in general.
