### ISSUE TITLE
FY2022: Complex Type typeProvidedBase

### ISSUE THREAD

**Issue by volkovai** [hmis-interop/xml#202]
Hi @eric-jahn ,

![image](https://user-images.githubusercontent.com/89135917/135846219-0db077b0-c743-4e69-a751-0a403c687521.png)

There are 9 possible values of attribute for TypeProvided tag in XML spec. But there is no possible value for "V2 Services Provided – SSVF (RecordType 144)".

Could you please take a look? Is this a bug?

Thank you,
Irina

**Comment by eric-jahn** [comment]
Great catch, thank you!  Fixed!
