### ISSUE TITLE
Schema Validation Errors

### ISSUE THREAD

**Issue by staylorclienttrack** [hmis-interop/xml#36]
We are receiving schema errors when validating:
![image](https://cloud.githubusercontent.com/assets/6115241/7186652/7c96f9a0-e428-11e4-83d6-d8044ce15cf4.png)
![image](https://cloud.githubusercontent.com/assets/6115241/7186655/8122cc6a-e428-11e4-9510-828062c6b6e3.png)

**Comment by eric-jahn** [comment]
Thanks, with which version of Saxon, and on which platform are you
validating it?


Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by staylorclienttrack** [comment]
Hi Eric,

I'm able to get the errors on this site:
http://www.utilities-online.info/xsdvalidation

Does that help?

Thanks

On Thu, Apr 16, 2015 at 11:11 AM, Eric Jahn <notifications@github.com>
wrote:

> Thanks, with which version of Saxon, and on which platform are you
> validating it?
>
>
> Eric Jahn
> Data Architect/IT Director
> Alexandria Consulting LLC
> St. Petersburg, Florida
> 727.537.9474
> alexandriaconsulting.com
>
> On Thu, Apr 16, 2015 at 1:05 PM, staylorclienttrack <
> notifications@github.com> wrote:
>
> > We are receiving schema errors when validating:
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/6115241/7186652/7c96f9a0-e428-11e4-83d6-d8044ce15cf4.png
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/6115241/7186655/8122cc6a-e428-11e4-9510-828062c6b6e3.png
> >
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hmis-interop/xml/issues/36>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hmis-interop/xml/issues/36#issuecomment-93787289>.
>



-- 
------------------------------
*Sam Taylor* | Director of Product Management | 801-451-2885 ex. 1700 |
www.ClientTrack.com

**Comment by eric-jahn** [comment]
I still can't tell what version of Saxon this instance of JAXP is using.
These kind of errors typically crop up when someone is trying to validate
1.1 XML Schema against 1.0 XML Schema.


Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by eric-jahn** [comment]
Yes, I'd validate with a known version of Saxon that supports 1.1:
http://saxon.sourceforge.net/


Eric Jahn
Data Architect/IT Director
Alexandria Consulting LLC
St. Petersburg, Florida
727.537.9474
alexandriaconsulting.com

**Comment by eric-jahn** [comment]
Can't determine the exact bug concisely, so I'm closing.
