### ISSUE TITLE
Pregnancy Status not included in Health Category enumeration

### ISSUE THREAD

**Issue by thockaday** [hmis-interop/xml#39]
Currently, healthCategory has the following enumeration (just including the annotation for brevity):

Health Category 27 = General Health Status 28 = Dental Health Status 29 = Mental Health Status

"30 = Pregnancy Status" probably needs to be added as a category. The DueDate element is already present but doesn't currently have a pregnancy value to pair with.

**Comment by eric-jahn** [comment]
Not sure how this one got missed.
