### ISSUE TITLE
DOB Element requires a valid date but when "Data not collected" no date exists 

### ISSUE THREAD

**Issue by staylorclienttrack** [hmis-interop/xml#47]
We are receiving validation errors on the DOB element. The element doesn't have a min occurences = 0 therefore a missing DOB element results in error of expected DOB element. Putting a blank elements returns invalid value error for DOB. NULL is expected when the birth date quality is 99.

**Comment by eric-jahn** [comment]
fixed by  8826719d4bb61bb0ec44ecf492fb59d83d4122d7

**Comment by eric-jahn** [comment]
good catch, btw :)
