### ISSUE TITLE
MonthsHomelessThisTime is validating as type="hmis:monthsHomelessPastThreeYears"

### ISSUE THREAD

**Issue by staylorclienttrack** [hmis-interop/xml#49]
The data standard for MonthsHomelessThisTime (Section 3.17, #3) is a number of months:
"Total number of months continuously homeless immediately prior to project entry
Text box for number of months (partial months i.e. 1 day – 30 days = 1 month"
but validation is looking for type="hmis:monthsHomelessPastThreeYears" which allow values [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 7, 8, 9, 99]'.

**Comment by eric-jahn** [comment]
Good catch also.
