### ISSUE TITLE
Race handling

### ISSUE THREAD

**Issue by steveconners** [hmis-interop/xml#52]
It appears that race is treated as a single value, while the API handles it as a multi-value attribute.

**Comment by eric-jahn** [comment]
Hey Steve, in the [2014 Data Dictionary](https://www.hudexchange.info/resources/documents/HMIS-Data-Dictionary.pdf), it reads "
Element Name Race
Field & Response(s) 1 Race (as many as are applicable)
1 American Indian or Alaska Native
2 Asian
3 Black or African American
4 Native Hawaiian or Other Pacific Islander
5 White
8 Client doesn’t know
9 Client refused
99 Data not collected
"
So you can indicated mixed race, with it, I surmise.  btw, this github repository (which is where HMIS keeps its tracked changed to the HMIS XML Schema) has no responsibility for or association with the unofficial software provider coordinated HMIS API you may be referring to.

**Comment by steveconners** [comment]
Got it. I missed the maxOccurs on the element. Thanks!
