### ISSUE TITLE
Project CoCID required for non head of household

### ISSUE THREAD

**Issue by staylorclienttrack** [hmis-interop/xml#55]
Client Location (3.16) is only required for the head of the household. We are getting validation errors for clients who don't have that data because they aren't head of household. 

Here are the rules in the CSV standard, maybe we can adopt something similiar here:
There must be at least one record in EnrollmentCoC with a DataCollectionStage of 1 for each ProjectEntryID in Enrollment.csv where RelationshipToHoH is equal to 1.  
There may be one or more additional records with a DataCollectionStage of 2 in the event that a household moves between continuums during an enrollment.  

Thanks

**Comment by eric-jahn** [comment]
Good catch.  This is because the logical model had been incorrect ... see https://github.com/hmis-interop/logical-model/issues/4 .
