### ISSUE TITLE
3.17 elements in version 4.1

### ISSUE THREAD

**Issue by staylorclienttrack** [hmis-interop/xml#57]
We ran into a couple of issues when updating XML to 3.17. 

First, a clarification on 3.17.1. The question has changed from "Continuously Homeless for at Least One Year" to "Client entering from the streets, ES, or SH." Will this data element remain in the XML element "ContinuoslyHomelessOneYear" or should it be something new? in the CSV it's EntryFromStreetESSH. 

I can't find an XML element for 3.17.A "Approximate Date Started"  in the CSV it's DateToStreetESSH. Please let me know which element we should use for this data point.

Thanks for your help

**Comment by eric-jahn** [comment]
@staylorclienttrack , the XML will mirror the CSV and Logical Model.  It just adds validation.  So ContinuoslyHomelessOneYear will be removed and EntryFromStreetESSH will be added.  Just to keep things consistent/less confusing, XML will also use DateToStreetESSH.
