### ISSUE TITLE
XML 4.1 - 4.44 VAMC Number and 4.45 VAMC Station Number

### ISSUE THREAD

**Issue by staylorclienttrack** [hmis-interop/xml#58]
I can't find these two new elements. In CSV they are HPScreeningScore and VAMCStation in enrollment.

**Comment by eric-jahn** [comment]
We don't have XML 4.1 posted yet, but it will be soon.  We just have 4.0.1 posted, which are just bug fixes to 4.0.

**Comment by eric-jahn** [comment]
Resolved by #77 and #78.
