### ISSUE TITLE
Dependent fields are null?

### ISSUE THREAD

**Issue by eric-jahn** [hmis-interop/xml#64]
from CSV 4.1: "Dependent fields will be null unless the parent field contains a value defined by the HMIS
Data Dictionary as triggering the dependent field."  So, we can't just omit the dependent element that may not be needed, as we did before?  This will lengthen the export size and not really convey any useful information.

**Comment by Arabica** [comment]
The dependent elements can be omitted in the XML.  Omitting a field in a CSV export isn't an option -- all fields have to be present in any given file -- so it's the values that are null there, but that doesn't have to be replicated in the XML.

**Comment by eric-jahn** [comment]
got it, that's what I thought ... but wanted to verify :)
