### ISSUE TITLE
HashStatus of SHA-1 RHY for name and SSN identifiers

### ISSUE THREAD

**Issue by eric-jahn** [hmis-interop/xml#70]
FirstName, MiddleName, LastName, and SSN – needs conditional data types exports with a HashStatus of SHA-1 RHY

**Comment by Arabica** [comment]
The RHY upload will be CSV only; this is not needed for HMIS XML.

Sent from my iPhone.

On Oct 13, 2015, at 2:20 AM, Eric Jahn <notifications@github.com<mailto:notifications@github.com>> wrote:


FirstName, MiddleName, LastName, and SSN - needs conditional data types exports with a HashStatus of SHA-1 RHY

-
Reply to this email directly or view it on GitHub<https://github.com/hmis-interop/xml/issues/70>.


________________________________
This message may contain privileged and confidential information intended solely for the addressee. Please do not read, disseminate or copy it unless you are the intended recipient. If this message has been received in error, we kindly ask that you notify the sender immediately by return email and delete all copies of the message from your system.

**Comment by eric-jahn** [comment]
Should I leave it in to give people a way to hash (just not specific to
RHY)?

**Comment by Arabica** [comment]
It's fine to leave it in there if it's already there.

**Comment by eric-jahn** [comment]
That's what I was hoping you'd say.  It's also useful for other scenarios
where they want to use SHA-1.  Maybe I'll just call it "SHA1", not
"SHA1RHY".  Then no confusion thinking it could be used for RHY.  It's
pretty cool how it's implemented now.  If you set the has flag to SHA1, it
changes the validation to look for a 44 or 40 character hash, instead of
the normal SSN/name validation.

**Comment by eric-jahn** [comment]
Closed by a99ef4721fe3ce7807220485e9ff7de41d7e84d6
